#开发环境
text: 开发环境
server:
  ip: 47.102.122.171

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.102.122.171:3306/university?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: university
    password: root

files:
  uploads:
    path: C:\Users\h\Desktop\uploads\
